import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import GlobalContext from '@/context/GlobalContext'
import { ThemeProvider } from '@/themeProvider/ThemeProvider'
import QueryProvider from '@/queryProvider/QueryProvider'
import { ToastContainer } from '@/nextToast/toast'
import 'react-toastify/dist/ReactToastify.css';
import Template from '@/animation/Template'
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <QueryProvider>
        <GlobalContext>
          <Template>

       {children}
       <ToastContainer />
          </Template>
       </GlobalContext>
        </QueryProvider>
       
       
        </body>
    </html>
  )
}
